### ISSUE TITLE
Add RadiusProfile to list_display in User changelist

### ISSUE THREAD

**Issue by rohithasrk** [openwisp/django-freeradius#146]

**Comment by nemesisdesign** [comment]
This would be useful but needs special care because it can break integration with larger systems (eg: immagine openwisp-radius plugged in a larger openwisp deployment with additional modules).

The first thing that comes into my mind is to be able to deactivate this with a setting but there may be other better ways to deal with that eventuality.

**Comment by nemesisdesign** [comment]
Development has moved to [openwisp-radius](https://github.com/openwisp/django-freeradius), this repository is going to be archived.
