### ISSUE TITLE
Handle Calling-Station-Id and Called-Station-Id in RadiusPostAuth

### ISSUE THREAD

**Issue by peppelinux** [openwisp/django-freeradius#165]
in /etc/freeradius/3.0/mods-config/sql/main/mysql/queries.conf the posth-auth insert query should be changed this way:
````
post-auth {
        query = "\
                INSERT INTO ${..postauth_table} \
                        (username, \
                         pass, \
                         reply, \
                         authdate, \
                         callingstationid, \
                         calledstationid \
                         ) \
                VALUES ( \
                        '%{SQL-User-Name}', \
                        '%{%{User-Password}:-%{Chap-Password}}', \
                        '%{reply:Packet-Type}', \
                        '%S', \
                        '%{Calling-Station-Id}', \
                        '%{Called-Station-Id}' \
                        )"
}
````
otherwise callingstationid and calledstationid in the sql schema will remains null.
This should be pushed into documentation if you agree

**Comment by nemesisdesign** [comment]
@peppelinux officially we are recommending to use the REST module for the postauth phase: http://django-freeradius.readthedocs.io/en/latest/general/freeradius.html#configure-the-rest-module

**Comment by peppelinux** [comment]
Only rest auth is the way to handle these attributes well in django-freeradius?

**Comment by nemesisdesign** [comment]
@peppelinux it's not the only way, but it's the recommended and documented way which we intend to support. that is: reply to and help people if they get stuck, add support for new features and so on.

Handling via the REST API gives infinite possibilities, it allows to hook django signals and perform operations that wouldn't be possible to perform with SQL queries. That's why we are investing in that direction.
