### ISSUE TITLE
[docs] Specify which steps are required when installing freeradius for development

### ISSUE THREAD

**Issue by EdoPut** [openwisp/django-freeradius#77]
In https://github.com/openwisp/django-freeradius/blob/master/docs/source/general/freeradius.rst we deal with installing and configuring freeradius with both a sql backend and a rest backend but we don't specify which is needed for development only.

As an example #75 had problems that deals with configuring freeradius and can't move on to more interesting work.

I suggest we begin with named sections and specify which are needed for development purpose only.

**Comment by peppelinux** [comment]
Could we open two task for 

ansible-freeradius
and
ansible-freeradius-dev

How this sounds to you?

**Comment by cappe87** [comment]
I agree!

Il mar 26 dic 2017, 13:56 Giuseppe De Marco <notifications@github.com> ha
scritto:

**Comment by peppelinux** [comment]
@cappe87 merry xmas :)

We could start extracting what we consider good for us, from this if you agree:
````
https://github.com/peppelinux/UniTools/blob/master/freeradius/freeradius_3.0.12_debian9.setup.sh
````

**Comment by peppelinux** [comment]
@EdoPut 
the guide is very very good!
https://github.com/openwisp/django-freeradius/blob/master/docs/source/general/freeradius.rst

**Comment by EdoPut** [comment]
Extracting the script steps to something more readable should be fine.

The guide is very good as it addresses how to configure freeradius but it's not done as it miss key points

- SQL is needed when developing?
- we don't refer that there is a dummy_sql module to remove

**Comment by nemesisdesign** [comment]
Let's keep it simple and advise to configure as we explain, expert users will figure it out by themselves if they don't need anything, newbies would get confused if we start branching the documentation into different cases.

I'm getting confused because we have different issues related to similar aspect of the docs:

- #53
- #75
- and this one #77

Is there any duplication among these 3 or can we make 3 different independent Google Code-In tasks?

**Comment by nemesisdesign** [comment]
thx for the status update
